---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-sops"
      ansible.builtin.include_role:
        name: "ansible-role-sops"
      vars:
        sops_version: "{{ lookup('env', 'sops_version') | default('latest', true) }}"
