---
- name: Verify
  hosts: all
  tasks:
    - name: Windows | Sops should be functionnal
      ansible.windows.win_command: sops --version
      register: sops_version_result

    - name: Windows | Verify commands outputs
      assert:
        that:
          - sops_version_result.rc == 0
        success_msg: "All tests passed"
