name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  test:
    name: ${{ matrix.image }} sops ${{ matrix.sops_version }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - almalinux:8
          - rockylinux:8
          - fedora:37
          - ubuntu:22.04
          - ubuntu:20.04
          - debian:12
          - debian:11
          - amazonlinux:2
          - opensuse:leap
          - archlinux:latest
          - alpine:latest
          - gentoo:latest
        sops_version:
          - latest
          - v3.7.3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Test Ansible role
        run: molecule test
        env:
          image: ansible-${{ matrix.image }}
          sops_version: ${{ matrix.sops_version }}

      - name: Test Ansible role with check_mode enable
        run: molecule check
        env:
          image: ansible-${{ matrix.image }}
          sops_version: ${{ matrix.sops_version }}
